---
title: "IATweight"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library(dplyr)
library(data.table)
library(ggplot2)
library(haven)
library(frequency)
library(psych)
library(foreign)
```

loading files in
```{r}
IAT04 <- read.spss("Implicit_datasets/Weight IAT.public.2004.sav", to.data.frame=TRUE)
IAT05 <- read.spss("Implicit_datasets/Weight IAT.public.2005.sav", to.data.frame=TRUE)
IAT06 <- read.spss("Implicit_datasets/Weight IAT.public.2006.sav", to.data.frame=TRUE)
IAT07 <- read.spss("Implicit_datasets/Weight IAT.public.2007.sav", to.data.frame=TRUE)
IAT08 <- read.spss("Implicit_datasets/Weight IAT.public.2008.sav", to.data.frame=TRUE)
IAT09 <- read.spss("Implicit_datasets/Weight IAT.public.2009.sav", to.data.frame=TRUE)
IAT10 <- read.spss("Implicit_datasets/Weight IAT.public.2010.revised.sav", to.data.frame=TRUE)
IAT11 <- read.spss("Implicit_datasets/Weight IAT.public.2011.revised332017.sav", to.data.frame=TRUE)
IAT12 <- read.spss("Implicit_datasets/Weight IAT.public.2012.revised.sav", to.data.frame=TRUE)
IAT13 <- read.spss("Implicit_datasets/Weight IAT.public.2013.revised.sav", to.data.frame=TRUE)
IAT14 <- read.spss("Implicit_datasets/Weight IAT.public.2014.revised.sav", to.data.frame=TRUE)
IAT15 <- read.spss("Implicit_datasets/Weight IAT.public.2015.sav", to.data.frame=TRUE)
IAT16 <- read.spss("Implicit_datasets/Weight IAT.public.2016.sav", to.data.frame=TRUE)
IAT17 <- read.spss("Implicit_datasets/Weight IAT.public.2017.sav", to.data.frame=TRUE)
IAT18 <- read.spss("Implicit_datasets/Weight_IAT.public.2018.sav", to.data.frame=TRUE)
IAT19 <- read.spss("Implicit_datasets/Weight IAT.public.2019.sav", to.data.frame=TRUE)
```

making tables
```{r}
table1 <- select(IAT04, D_biep.Thin_Good_all,att_5, tfat, tthin, sex, STATE)
table1 <- as.data.frame(table1)

table2 <- select(IAT05, D_biep.Thin_Good_all,att_5, tfat,tthin, sex, STATE)
table2 <- as.data.frame(table2)

table3 <- select(IAT06, D_biep.Thin_Good_all,att_5, tfat,tthin, sex, STATE)
table3 <- as.data.frame(table3)

table4 <- select(IAT07, D_biep.Thin_Good_all,att_7, tfat,tthin, sex, STATE)
table4 <- as.data.frame(table4)

table5 <- select(IAT08, D_biep.Thin_Good_all,att_7,tfat,tthin, sex, STATE)
table5 <- as.data.frame(table5)

table6 <- select(IAT09, D_biep.Thin_Good_all,att_7,tfat,tthin, sex, STATE)
table6 <- as.data.frame(table6)

table7 <- select(IAT10, D_biep.Thin_Good_all,att_7,att_reversed,tfat,tfat_1to11_reversed,tthin,tthin_1to11_reversed,dem_sex, sex, STATE)
table7 <- as.data.frame(table7)

table8 <- select(IAT11, D_biep.Thin_Good_all, att_reversed, tfat_1to11_reversed, tthin_1to11_reversed,dem_sex, STATE)
table8 <- as.data.frame(table8)

table9 <- select(IAT12, D_biep.Thin_Good_all, att_reversed, tfat_1to11_reversed, tthin_1to11_reversed,dem_sex, STATE)
table9 <- as.data.frame(table9)

table10 <- select(IAT13, D_biep.Thin_Good_all, att_reversed, tfat_1to11_reversed, tthin_1to11_reversed, dem_sex, STATE)
table10 <- as.data.frame(table10)

table11 <- select(IAT14, D_biep.Thin_Good_all, att_reversed, tfat_1to11_reversed, tthin_1to11_reversed,dem_sex, STATE)
table11 <- as.data.frame(table11)

table12 <- select(IAT15, D_biep.Thin_Good_all, weightpref_001, tempfat_001, tempthin_001,sex, STATE)
table12 <- as.data.frame(table12)

table13 <- select(IAT16, D_biep.Thin_Good_all,weightpref_001,att7, tfat,tempfat_001, tthin,tempthin_001,sex, birthsex, STATE)
table13 <- as.data.frame(table13)

table14 <- select(IAT17, D_biep.Thin_Good_all, att7, tfat, tthin, birthsex, STATE)
table14 <- as.data.frame(table14)

IAT18$birthsex <- IAT18$birthSex
table15 <- select(IAT18, D_biep.Thin_Good_all, att7, tfat, tthin, birthSex, STATE)
colnames(table15)[5] <- "birthsex"
table15 <- as.data.frame(table15)

IAT18$birthsex <- IAT18$birthSex
table15 <- select(IAT18, D_biep.Thin_Good_all, att7, tfat, tthin, birthSex, STATE)
table15 <- as.data.frame(table15)

```

making clusters
```{r}
cluster1 <- rbind(table1,table2,table3)
cluster2<- rbind(table4,table5,table6)
cluster3 <- table7
cluster4 <- rbind(table8,table9,table10,table11)
cluster5 <- table12
cluster6 <- table13
cluster7 <- rbind(table14,table15)
```

IAT scores
```{r}
##removing NAs for IAT
weight1 <- cluster1[(!(is.na(cluster1$D_biep.Thin_Good_all))),]
weight2<- cluster2[(!(is.na(cluster2$D_biep.Thin_Good_all))),]
weight3 <- cluster3[(!(is.na(cluster3$D_biep.Thin_Good_all))),]
weight4 <- cluster4[(!(is.na(cluster4$D_biep.Thin_Good_all))),]
weight5 <- cluster5[(!(is.na(cluster5$D_biep.Thin_Good_all))),]
weight6 <- cluster6[(!(is.na(cluster6$D_biep.Thin_Good_all))),]
weight7 <- cluster7[(!(is.na(cluster7$D_biep.Thin_Good_all))),]

#removing NAs for sex
weight1.IAT <- dplyr::select(weight1,D_biep.Thin_Good_all,sex) %>% filter(sex != "n", sex!= "", sex!= ".", sex!= "n", sex!="1", sex!= "M", sex!= "F",sex != "A")

weight2.IAT <- dplyr::select(weight2,D_biep.Thin_Good_all,sex) %>% filter(sex != "n", sex!= "", sex!= ".", sex!= "n", sex!="1", sex!= "M", sex!= "F",sex != "A")

weight3dem.IAT <- dplyr::select(weight3,D_biep.Thin_Good_all,dem_sex) %>% filter(dem_sex != "n", dem_sex!= "", dem_sex!= ".", dem_sex!= "n", dem_sex!= "M", dem_sex!= "F", dem_sex != "A")

weight3sex.IAT <- dplyr::select(weight3,D_biep.Thin_Good_all,sex) %>% filter(sex != "n", sex!= "", sex!= ".", sex!= "n", sex!="1", sex!= "M", sex!= "F",sex != "A")

weight4.IAT <- dplyr::select(weight4,D_biep.Thin_Good_all,dem_sex) %>% filter(dem_sex != "n", dem_sex!= "", dem_sex!= ".", dem_sex!= "n", dem_sex!= "M", dem_sex!= "F", dem_sex != "A")

weight5.IAT <- dplyr::select(weight5,D_biep.Thin_Good_all,sex) %>% filter(sex != "n", sex!= "", sex!= ".", sex!= "n", sex!="1", sex!= "M", sex!= "F",sex != "A")

weight6sex.IAT <- dplyr::select(weight6,D_biep.Thin_Good_all,sex) %>% filter(sex != "n", sex!= "", sex!= ".", sex!= "n", sex!="1", sex!= "M", sex!= "F",sex != "A")

weight6birth.IAT <- dplyr::select(weight6,D_biep.Thin_Good_all,birthsex) %>% filter(birthsex != "n", birthsex!= "", birthsex!= ".", birthsex!= "n", birthsex!="1", birthsex!= "M", birthsex!= "F",birthsex != "A")

weight7.IAT <- dplyr::select(weight7,D_biep.Thin_Good_all,birthsex) %>% filter(birthsex != "n", birthsex!= "", birthsex!= ".", birthsex!= "n", birthsex!="1", birthsex!= "M", birthsex!= "F",birthsex != "A")

##renaming gender variables
weight3dem.IAT$sex <- weight3dem.IAT$dem_sex
weight4.IAT$sex <- weight4.IAT$dem_sex
weight6birth.IAT$sex <- weight6birth.IAT$birthsex
weight7.IAT$sex <- weight7.IAT$birthsex

#combining datasets
IATweight <- rbind(weight1.IAT,weight2.IAT,weight3dem.IAT[,c(1,3)],weight3sex.IAT,weight4.IAT[,c(1,3)],weight5.IAT,weight6birth.IAT[,c(1,3)],weight6sex.IAT,weight7.IAT[,c(1,3)])

#renaming gender variables to all be sex
IATweight <- 
  IATweight %>%
  mutate(sex = case_when(
    sex == "male" ~ "Male",
    sex == "Male" ~ "Male",
    sex == "female" ~ "Female",
    sex == "Female" ~ "Female"))

### filtering by sex
IAT.m <- IATweight %>% filter(sex == "Male")

IAT.f <- IATweight %>% filter(sex =="Female")

#histogram
ggplot(IATweight, aes(D_biep.Thin_Good_all, fill = sex)) + geom_histogram(alpha=0.5, position="identity") + ggtitle("Histogram of D_biep.Thin_Good_all by gender")

#summary statistics and tests
Mode <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}


describe(IAT.m)
IQR(IAT.m$D_biep.Thin_Good_all)
Mode(IAT.m$D_biep.Thin_Good_all)

describe(IAT.f)
IQR(IAT.f$D_biep.Thin_Good_all)
Mode(IAT.f$D_biep.Thin_Good_all)

t.test(IAT.m$D_biep.Thin_Good_all, IAT.f$D_biep.Thin_Good_all)
var.test(IAT.m$D_biep.Thin_Good_all, IAT.f$D_biep.Thin_Good_all)
```


Att scores
```{r}
##removing NAs for att
att1 <- cluster1[(!(is.na(cluster1$att_5))),]
att2 <- cluster2[(!(is.na(cluster2$att_7))),]
att3a <- cluster3[(!(is.na(cluster3$att_7))),]
att3b <- cluster3[(!(is.na(cluster3$att_reversed))),]
att4 <- cluster4[(!(is.na(cluster4$att_reversed))),]
att5 <- cluster5[(!(is.na(cluster5$weightpref_001))),]
att6a <- cluster6[(!(is.na(cluster6$weightpref_001))),]
att6b <- cluster6[(!(is.na(cluster6$att7))),]
att.7 <- cluster7[(!(is.na(cluster7$att7))),]

#removing NAs for sex
weight1.att <- dplyr::select(att1,att_5,sex) %>% filter(sex != "n", sex!= "", sex!= ".", sex!= "n", sex!="1", sex!= "M", sex!= "F",sex != "A")

weight2.att <- dplyr::select(att2,att_7,sex) %>% filter(sex != "n", sex!= "", sex!= ".", sex!= "n", sex!="1", sex!= "M", sex!= "F",sex != "A")

weight3b.att <- dplyr::select(att3b,att_reversed,dem_sex) %>% filter(dem_sex != "n", dem_sex!= "", dem_sex!= ".", dem_sex!= "n", dem_sex!= "M", dem_sex!= "F", dem_sex != "A")

weight3a.att <- dplyr::select(att3a,att_7,sex) %>% filter(sex != "n", sex!= "", sex!= ".", sex!= "n", sex!="1", sex!= "M", sex!= "F",sex != "A")

weight4.att <- dplyr::select(att4,att_reversed,dem_sex) %>% filter(dem_sex != "n", dem_sex!= "", dem_sex!= ".", dem_sex!= "n", dem_sex!= "M", dem_sex!= "F", dem_sex != "A")

weight5.att <- dplyr::select(att5,weightpref_001,sex) %>% filter(sex != "n", sex!= "", sex!= ".", sex!= "n", sex!="1", sex!= "M", sex!= "F",sex != "A")

weight6a.att <- dplyr::select(att6a,weightpref_001,sex) %>% filter(sex != "n", sex!= "", sex!= ".", sex!= "n", sex!="1", sex!= "M", sex!= "F",sex != "A")

weight6b.att <- dplyr::select(att6b,att7,birthsex) %>% filter(birthsex != "n", birthsex!= "", birthsex!= ".", birthsex!= "n", birthsex!="1", birthsex!= "M", birthsex!= "F",birthsex != "A")

weight7.att <- dplyr::select(att.7,att7,birthsex) %>% filter(birthsex != "n", birthsex!= "", birthsex!= ".", birthsex!= "n", birthsex!="1", birthsex!= "M", birthsex!= "F",birthsex != "A", att7 != -999)

##renaming gender variables
weight3b.att$sex <- weight3b.att$dem_sex
weight4.att$sex <- weight4.att$dem_sex
weight6b.att$sex <- weight6b.att$birthsex
weight7.att$sex <- weight7.att$birthsex

#renaming att variables
weight1.att$att <- weight1.att$att_5
weight2.att$att <- weight2.att$att_7
weight3a.att$att <- weight3a.att$att_7
weight3b.att$att <- weight3b.att$att_reversed
weight4.att$att <- weight4.att$att_reversed
weight5.att$att <- weight5.att$weightpref_001
weight6a.att$att <- weight6a.att$weightpref_001
weight6b.att$att <- weight6b.att$att7
weight7.att$att <- weight7.att$att7

#transforming variable and standardizing scales
weight1.att <- 
  weight1.att %>%
  mutate(att = case_when(
    att == "I strongly prefer fat people to thin people." ~ 1,
    att == "I moderately prefer fat people to thin people." ~ 2,
    att == "I like thin people and fat people equally" ~ 3,
    att == "I moderately prefer thin people to fat people." ~ 4,
    att == "I strongly prefer thin people to fat people." ~ 5))
weight1.att$att <- (weight1.att$att - mean(weight1.att$att)) / sd(weight1.att$att)

#combining datasets, transforming variable, and standardizing
attWeighta <- rbind.data.frame(weight2.att[,c(2,3)],weight3a.att[,c(2,3)],weight5.att[,c(2,3)],weight6a.att[,c(2,3)],weight6b.att[,c(4,3)],weight7.att[,c(4,3)])

attWeighta <- 
  attWeighta %>%
  mutate(att = case_when(
    att == "I strongly prefer Fat People to Thin People." ~ 1,
    att == "I moderately prefer Fat People to Thin People." ~ 2,
    att == "I slightly prefer Fat People to Thin People." ~ 3,
    att == "I like Thin People and Fat People equally." ~ 4,
    att == "I slightly prefer Thin People to Fat People." ~ 5,
    att == "I moderately prefer Thin People to Fat People." ~ 6,
    att == "I strongly prefer Thin People to Fat People" ~ 7,))

attWeightb <- rbind.data.frame(attWeighta, weight3b.att[,c(3,4)],weight4.att[,c(3,4)])

attWeightb$att <- (attWeightb$att - mean(attWeightb$att)) / sd(attWeightb$att)

#combining datasets and renaming gender variables to all be sex
attWeightfull <- rbind(weight1.att[,c(2,3)],attWeightb)

attWeightfull <- 
  attWeightfull %>%
  mutate(sex = case_when(
    sex == "male" ~ "Male",
    sex == "Male" ~ "Male",
    sex == "female" ~ "Female",
    sex == "Female" ~ "Female"))

### filtering by sex
att.m <- attWeightfull %>% filter(sex == "Male")

att.f <- attWeightfull %>% filter(sex =="Female")

#histogram
ggplot(attWeightfull, aes(att, fill = sex)) + geom_histogram(alpha=0.5, position="identity") + ggtitle("Histogram of att by gender")

#summary statistics and tests
describe(att.m$att)
IQR(att.m$att)
Mode(att.m$att)

describe(att.f$att)
IQR(att.f$att)
Mode(att.f$att)

t.test(att.m$att, att.f$att)
var.test(att.m$att, att.f$att)
```


tfat
```{r}
##removing NAs for tfat
tfat1 <- cluster1[(!(is.na(cluster1$tfat))),]
tfat2 <- cluster2[(!(is.na(cluster2$tfat))),]
tfat3a <- cluster3[(!(is.na(cluster3$tfat))),]
tfat3b <- cluster3[(!(is.na(cluster3$tfat_1to11_reversed))),]
tfat4 <- cluster4[(!(is.na(cluster4$tfat_1to11_reversed))),]
tfat5 <- cluster5[(!(is.na(cluster5$tempfat_001))),]
tfat6a <- cluster6[(!(is.na(cluster6$tempfat_001))),]
tfat6b <- cluster6[(!(is.na(cluster6$tfat))),]
tfat7 <- cluster7[(!(is.na(cluster7$tfat))),]

#removing NAs for sex
weight1.tfat <- dplyr::select(tfat1,tfat,sex) %>% filter(sex != "n", sex!= "", sex!= ".", sex!= "n", sex!="1", sex!= "M", sex!= "F",sex != "A")

weight2.tfat <- dplyr::select(tfat2,tfat,sex) %>% filter(sex != "n", sex!= "", sex!= ".", sex!= "n", sex!="1", sex!= "M", sex!= "F",sex != "A")

weight3b.tfat <- dplyr::select(tfat3b,tfat_1to11_reversed,dem_sex) %>% filter(dem_sex != "n", dem_sex!= "", dem_sex!= ".", dem_sex!= "n", dem_sex!= "M", dem_sex!= "F", dem_sex != "A")

weight3a.tfat <- dplyr::select(tfat3a,tfat,sex) %>% filter(sex != "n", sex!= "", sex!= ".", sex!= "n", sex!="1", sex!= "M", sex!= "F",sex != "A")

weight4.tfat <- dplyr::select(att4,tfat_1to11_reversed,dem_sex) %>% filter(dem_sex != "n", dem_sex!= "", dem_sex!= ".", dem_sex!= "n", dem_sex!= "M", dem_sex!= "F", dem_sex != "A")

weight5.tfat <- dplyr::select(tfat5,tempfat_001,sex) %>% filter(sex != "n", sex!= "", sex!= ".", sex!= "n", sex!="1", sex!= "M", sex!= "F",sex != "A")

weight6a.tfat <- dplyr::select(tfat6a,tempfat_001,sex) %>% filter(sex != "n", sex!= "", sex!= ".", sex!= "n", sex!="1", sex!= "M", sex!= "F",sex != "A")

weight6b.tfat <- dplyr::select(tfat6b,tfat,birthsex) %>% filter(birthsex != "n", birthsex!= "", birthsex!= ".", birthsex!= "n", birthsex!="1", birthsex!= "M", birthsex!= "F",birthsex != "A")

weight7.tfat <- dplyr::select(tfat7,tfat,birthsex) %>% filter(birthsex != "n", birthsex!= "", birthsex!= ".", birthsex!= "n", birthsex!="1", birthsex!= "M", birthsex!= "F",birthsex != "A")

##renaming gender variables
weight3b.tfat$sex <- weight3b.tfat$dem_sex
weight4.tfat$sex <- weight4.tfat$dem_sex
weight6b.tfat$sex <- weight6b.tfat$birthsex
weight7.tfat$sex <- weight7.tfat$birthsex

#renaming att variables
weight3b.tfat$tfat <- weight3b.tfat$tfat_1to11_reversed
weight4.tfat$tfat <- weight4.tfat$tfat_1to11_reversed
weight5.tfat$tfat <- weight5.tfat$tempfat_001
weight6a.tfat$tfat <- weight6a.tfat$tempfat_001

#transforming variable and standardizing scales
weight1.tfat <- 
  weight1.tfat %>%
  mutate(tfat = case_when(
    tfat == "0 very cold" ~ 0,
    tfat == "1" ~ 1,
    tfat == "2" ~ 2,
    tfat == "3" ~ 3,
    tfat == "4" ~ 4,
    tfat == "5 neutral" ~ 5,
    tfat == "6" ~ 6,
    tfat == "7" ~ 7,
    tfat == "8" ~ 8,
    tfat == "9" ~ 9,
    tfat == "10 very warm" ~ 10))

weight2.tfat <- 
  weight2.tfat %>%
  mutate(tfat = case_when(
    tfat == "0 very cold" ~ 0,
    tfat == "1" ~ 1,
    tfat == "2" ~ 2,
    tfat == "3" ~ 3,
    tfat == "4" ~ 4,
    tfat == "5 neutral" ~ 5,
    tfat == "6" ~ 6,
    tfat == "7" ~ 7,
    tfat == "8" ~ 8,
    tfat == "9" ~ 9,
    tfat == "10 very warm" ~ 10))

weight3a.tfat <- 
  weight3a.tfat %>%
  mutate(tfat = case_when(
    tfat == "0 very cold" ~ 0,
    tfat == "1" ~ 1,
    tfat == "2" ~ 2,
    tfat == "3" ~ 3,
    tfat == "4" ~ 4,
    tfat == "5 neutral" ~ 5,
    tfat == "6" ~ 6,
    tfat == "7" ~ 7,
    tfat == "8" ~ 8,
    tfat == "9" ~ 9,
    tfat == "10 very warm" ~ 10))

weight1a <- rbind(weight1.tfat,weight2.tfat,weight3a.tfat)

weight1b <- rbind(weight3b.tfat[,c(3,4)],weight4.tfat[,c(3,4)],weight5.tfat[,c(3,2)],weight6a.tfat[,c(3,2)],weight6b.tfat[,c(3,1)],weight7.tfat[,c(3,1)])

weight1b <- 
  weight1b %>%
  mutate(tfat = case_when(
    tfat == "Extremely cold" ~ 0,
    tfat == "Very cold" ~ 1,
    tfat == "Moderately cold" ~ 2,
    tfat == "Somewhat cold" ~ 3,
    tfat == "Slightly cold" ~ 4,
    tfat == "Neither warm nor cold" ~ 5,
    tfat == "Neutral" ~ 5,
    tfat == "Slightly warm" ~ 6,
    tfat == "Somewhat warm" ~ 7,
    tfat == "Moderately warm" ~ 8,
    tfat == "Very warm" ~ 9,
    tfat == "Extremely warm" ~ 10))

weight1b <- weight1b[(!(is.na(weight1b$tfat))),]

tfatFull <- rbind(weight1a,weight1b)

tfatFull <- 
  tfatFull %>%
  mutate(sex = case_when(
    sex == "male" ~ "Male",
    sex == "Male" ~ "Male",
    sex == "female" ~ "Female",
    sex == "Female" ~ "Female"))

#standardizing the thermometers
tfatFull$tfat <- (tfatFull$tfat - mean(tfatFull$tfat)) / sd(tfatFull$tfat)

### filtering by sex
tfat.m <- tfatFull %>% filter(sex == "Male")

tfat.f <- tfatFull %>% filter(sex =="Female")

#histogram
ggplot(tfatFull, aes(tfat, fill = sex)) + geom_histogram(alpha=0.5, position="identity") + ggtitle("Histogram of tfat by gender")

#summary statistics and tests
describe(tfat.m$tfat)
IQR(tfat.m$tfat)
Mode(tfat.m$tfat)

describe(tfat.f$tfat)
IQR(tfat.f$tfat)
Mode(tfat.f$tfat)

t.test(tfat.m$tfat, tfat.f$tfat)
var.test(tfat.m$tfat, tfat.f$tfat)
```

tthin
```{r}
##removing NAs for tthin
tthin1 <- cluster1[(!(is.na(cluster1$tthin))),]
tthin2 <- cluster2[(!(is.na(cluster2$tthin))),]
tthin3a <- cluster3[(!(is.na(cluster3$tthin))),]
tthin3b <- cluster3[(!(is.na(cluster3$tthin_1to11_reversed))),]
tthin4 <- cluster4[(!(is.na(cluster4$tthin_1to11_reversed))),]
tthin5 <- cluster5[(!(is.na(cluster5$tempthin_001))),]
tthin6a <- cluster6[(!(is.na(cluster6$tempthin_001))),]
tthin6b <- cluster6[(!(is.na(cluster6$tthin))),]
tthin7 <- cluster7[(!(is.na(cluster7$tthin))),]

#removing NAs for sex
weight1.tthin <- dplyr::select(tthin1,tthin,sex) %>% filter(sex != "n", sex!= "", sex!= ".", sex!= "n", sex!="1", sex!= "M", sex!= "F",sex != "A")

weight2.tthin <- dplyr::select(tthin2,tthin,sex) %>% filter(sex != "n", sex!= "", sex!= ".", sex!= "n", sex!="1", sex!= "M", sex!= "F",sex != "A")

weight3b.tthin <- dplyr::select(tthin3b,tthin_1to11_reversed,dem_sex) %>% filter(dem_sex != "n", dem_sex!= "", dem_sex!= ".", dem_sex!= "n", dem_sex!= "M", dem_sex!= "F", dem_sex != "A")

weight3a.tthin <- dplyr::select(tthin3a,tthin,sex) %>% filter(sex != "n", sex!= "", sex!= ".", sex!= "n", sex!="1", sex!= "M", sex!= "F",sex != "A")

weight4.tthin <- dplyr::select(att4,tthin_1to11_reversed,dem_sex) %>% filter(dem_sex != "n", dem_sex!= "", dem_sex!= ".", dem_sex!= "n", dem_sex!= "M", dem_sex!= "F", dem_sex != "A")

weight5.tthin <- dplyr::select(tthin5,tempthin_001,sex) %>% filter(sex != "n", sex!= "", sex!= ".", sex!= "n", sex!="1", sex!= "M", sex!= "F",sex != "A")

weight6a.tthin <- dplyr::select(tthin6a,tempthin_001,sex) %>% filter(sex != "n", sex!= "", sex!= ".", sex!= "n", sex!="1", sex!= "M", sex!= "F",sex != "A")

weight6b.tthin <- dplyr::select(tthin6b,tthin,birthsex) %>% filter(birthsex != "n", birthsex!= "", birthsex!= ".", birthsex!= "n", birthsex!="1", birthsex!= "M", birthsex!= "F",birthsex != "A")

weight7.tthin <- dplyr::select(tthin7,tthin,birthsex) %>% filter(birthsex != "n", birthsex!= "", birthsex!= ".", birthsex!= "n", birthsex!="1", birthsex!= "M", birthsex!= "F",birthsex != "A")

##renaming gender variables
weight3b.tthin$sex <- weight3b.tthin$dem_sex
weight4.tthin$sex <- weight4.tthin$dem_sex
weight6b.tthin$sex <- weight6b.tthin$birthsex
weight7.tthin$sex <- weight7.tthin$birthsex

#renaming att variables
weight3b.tthin$tthin <- weight3b.tthin$tthin_1to11_reversed
weight4.tthin$tthin <- weight4.tthin$tthin_1to11_reversed
weight5.tthin$tthin <- weight5.tthin$tempthin_001
weight6a.tthin$tthin <- weight6a.tthin$tempthin_001

#transforming variable and standardizing scales
weight1.tthin <- 
  weight1.tthin %>%
  mutate(tthin = case_when(
    tthin == "0 very cold" ~ 0,
    tthin == "1" ~ 1,
    tthin == "2" ~ 2,
    tthin == "3" ~ 3,
    tthin == "4" ~ 4,
    tthin == "5 neutral" ~ 5,
    tthin == "6" ~ 6,
    tthin == "7" ~ 7,
    tthin == "8" ~ 8,
    tthin == "9" ~ 9,
    tthin == "10 very warm" ~ 10))

weight2.tthin <- 
  weight2.tthin %>%
  mutate(tthin = case_when(
    tthin == "0 very cold" ~ 0,
    tthin == "1" ~ 1,
    tthin == "2" ~ 2,
    tthin == "3" ~ 3,
    tthin == "4" ~ 4,
    tthin == "5 neutral" ~ 5,
    tthin == "6" ~ 6,
    tthin == "7" ~ 7,
    tthin == "8" ~ 8,
    tthin == "9" ~ 9,
    tthin == "10 very warm" ~ 10))

weight3a.tthin <- 
  weight3a.tthin %>%
  mutate(tthin = case_when(
    tthin == "0 very cold" ~ 0,
    tthin == "1" ~ 1,
    tthin == "2" ~ 2,
    tthin == "3" ~ 3,
    tthin == "4" ~ 4,
    tthin == "5 neutral" ~ 5,
    tthin == "6" ~ 6,
    tthin == "7" ~ 7,
    tthin == "8" ~ 8,
    tthin == "9" ~ 9,
    tthin == "10 very warm" ~ 10))

thin1a <- rbind(weight1.tthin,weight2.tthin,weight3a.tthin)

thin1b <- rbind(weight3b.tthin[,c(3,4)],weight4.tthin[,c(3,4)],weight5.tthin[,c(3,2)],weight6a.tthin[,c(3,2)],weight6b.tthin[,c(3,1)],weight7.tthin[,c(3,1)])

thin1b <- 
  thin1b %>%
  mutate(tthin = case_when(
    tthin == "Extremely cold" ~ 0,
    tthin == "Very cold" ~ 1,
    tthin == "Moderately cold" ~ 2,
    tthin == "Somewhat cold" ~ 3,
    tthin == "Slightly cold" ~ 4,
    tthin == "Neither warm nor cold" ~ 5,
    tthin == "Neutral" ~ 5,
    tthin == "Slightly warm" ~ 6,
    tthin == "Somewhat warm" ~ 7,
    tthin == "Moderately warm" ~ 8,
    tthin == "Very warm" ~ 9,
    tthin == "Extremely warm" ~ 10))

thin1b <- thin1b[(!(is.na(thin1b$tthin))),]

tthinFull <- rbind(thin1a,thin1b)

tthinFull <- 
  tthinFull %>%
  mutate(sex = case_when(
    sex == "male" ~ "Male",
    sex == "Male" ~ "Male",
    sex == "female" ~ "Female",
    sex == "Female" ~ "Female"))

#standardizing the thermometers
tthinFull$tthin <- (tthinFull$tthin - mean(tthinFull$tthin)) / sd(tthinFull$tthin)

### filtering by sex
tthin.m <- tthinFull %>% filter(sex == "Male")

tthin.f <- tthinFull %>% filter(sex =="Female")

#histogram
ggplot(tthinFull, aes(tthin, fill = sex)) + geom_histogram(alpha=0.5, position="identity") + ggtitle("Histogram of tthin by gender")

#summary statistics and tests
describe(tthin.m$tthin)
IQR(tthin.m$tthin)
Mode(tthin.m$tthin)

describe(tthin.f$tthin)
IQR(tthin.f$tthin)
Mode(tthin.f$tthin)

t.test(tthin.m$tthin, tthin.f$tthin)
var.test(tthin.m$tthin, tthin.f$tthin)
```






